src/CineProject/PublicBundle/Entity/Actor.php
<?php

namespace CineProject\PublicBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Actor
 *
 * @ORM\Table(name="actor")
 * @ORM\Entity(repositoryClass="CineProject\PublicBundle\Repository\ActorRepository")
 */
class Actor
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255)
     */
    private $lastName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birth_date", type="datetime")
     */
    private $birthDate;

    /**
     * @var string
     *
     * @ORM\Column(name="biography", type="text")
     */
    private $biography;

    /**
     * @ORM\ManyToMany(targetEntity="CineProject\PublicBundle\Entity\Movie", mappedBy="actors")
     */
    private $movies;

    /**
     * @ORM\OneToOne(targetEntity="CineProject\PublicBundle\Entity\Image", cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=50)
     * @Gedmo\Slug(fields={"firstName","lastName"}, separator="-")
     */
    private $slug;


    public function __construct()
    {
        $this->movies = new ArrayCollection();
    }

    public function getFullName()
    {
        return $this->firstName.' '.$this->lastName;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Actor
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string 
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set birthDate
     *
     * @param \DateTime $birthDate
     * @return Actor
     */
    public function setBirthDate($birthDate)
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    /**
     * Get birthDate
     *
     * @return \DateTime 
     */
    public function getBirthDate()
    {
        return $this->birthDate;
    }

    /**
     * Set biography
     *
     * @param string $biography
     * @return Actor
     */
    public function setBiography($biography)
    {
        $this->biography = $biography;

        return $this;
    }

    /**
     * Get biography
     *
     * @return string 
     */
    public function getBiography()
    {
        return $this->biography;
    }

    /**
     * Add movies
     *
     * @param \CineProject\PublicBundle\Entity\Movie $movies
     * @return Actor
     */
    public function addMovie(\CineProject\PublicBundle\Entity\Movie $movies)
    {
        $this->movies[] = $movies;
        return $this;
    }

    /**
     * Remove movies
     *
     * @param \CineProject\PublicBundle\Entity\Movie $movies
     */
    public function removeMovie(\CineProject\PublicBundle\Entity\Movie $movies)
    {
        $this->movies->removeElement($movies);
    }

    /**
     * Get movies
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMovies()
    {
        return $this->movies;
    }

    /**
     * Set image
     *
     * @param \CineProject\PublicBundle\Entity\Image $image
     * @return Actor
     */
    public function setImage(\CineProject\PublicBundle\Entity\Image $image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return \CineProject\PublicBundle\Entity\Image 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Actor
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Actor
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }
}

src/CineProject/PublicBundle/Controller/DefaultController.php
<?php

namespace CineProject\PublicBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $bestMovies = $em->getRepository('CineProjectPublicBundle:Movie')->findBestMovies();
        return $this->render('CineProjectPublicBundle:Default:index.html.twig', array('bestMovies' => $bestMovies));
    }

    public function searchAction(Request $request)
    {
        $results = null;

        $search = $request->query->get('req'); // $_GET
        if($search){
            $em = $this->getDoctrine()->getManager();
            $results = $em->getRepository('CineProjectPublicBundle:Movie')->search($search);
        }

        return $this->render('CineProjectPublicBundle:Default:search.html.twig', array(
            'results' => $results,
            'search' => $search
        ));

    }
}

src/CineProject/PublicBundle/Resources/views/Default/index.html.twig
{% extends 'CineProjectPublicBundle::layout.html.twig' %}

{% block body %}
	<p>Meilleurs films :</p>
	<ul>
		{% for bestMovie in bestMovies %}
			<li>
				<p>Titre : <a href="{{ path('movie_show', {id: bestMovie.id}) }}">{{ bestMovie.title }}</a></p>
				<p>Note :{{ bestMovie.grade }}</p>
			</li>
		{% endfor %}
	</ul>
{% endblock %}

src/CineProject/PublicBundle/Resources/views/Default/search.html.twig
{% extends 'CineProjectPublicBundle::layout.html.twig' %}

{% block body %}
	<form action="{{ path('cine_project_public_search') }}">
		<label>Rechercher : <input type="text" name="req"></label>
		<input type="submit" value="ok">
	</form>
	{% if results %}
		{% if results.movies|length == 0 and results.actors|length == 0 and results.directors|length == 0%}
			<p>Aucun résultat pour <strong>{{ search }}</strong></p>
		{% else %}
			<p>Résultats pour <strong>{{ search }}</strong></p>
			<p>Films :</p>
			<ul>
				{% for movie in results.movies %}
					<li><a href="{{ path('movie_show', {id: movie.id}) }}">{{ movie.title }}</a></li>
				{% endfor %}
			</ul>
			<p>Acteurs :</p>
			<ul>
				{% for actor in results.actors %}
					<li><a href="{{ path('actor_show', {slug: actor.slug}) }}">{{ actor.fullName }}</a></li>
				{% endfor %}
			</ul>
			<p>Réalisateurs :</p>
			<ul>
				{% for director in results.directors %}
					<li><a href="{{ path('director_show', {id: director.id}) }}">{{ director.fullName }}</a></li>
				{% endfor %}
			</ul>
		{% endif %}
	{% endif %}

{% endblock %}